In [2]:
import numpy as np
import scipy.stats as stats

In [41]:
dim = 2
D = np.zeros([dim,dim,dim])

D[0,0,0] = 0.1
D[0,1,1] = 0.4
D[1,0,0] = 0.2
D[1,1,1] = 0.3


         
print('\n probs on x,y,z (z are the layers):')
print(D[:,:,0])
print(D[:,:,1])

print('\n P(x):')
print(np.sum(D, axis=1).sum(axis=1))

print('\n p(y):')
print(np.sum(D, axis=0).sum(axis=1))

print('\n p(z):')
print(np.sum(D, axis=0).sum(axis=0))

print('\n p(x, y):')
print(np.sum(D, axis=2))

print('\n p(x|y):')
print(np.sum(D, axis=2) * 2)

print('\n p(x, z):')
print(np.sum(D, axis=1))

print('\n p(x|z):')
print(np.sum(D, axis=1) * 2)

print('\n p(y|z):')
print(np.sum(D, axis=0) * 2)


 probs on x,y,z (z are the layers):
[[0.1 0. ]
 [0.2 0. ]]
[[0.  0.4]
 [0.  0.3]]

 P(x):
[0.5 0.5]

 p(y):
[0.3 0.7]

 p(z):
[0.3 0.7]

 p(x, y):
[[0.1 0.4]
 [0.2 0.3]]

 p(x|y):
[[0.2 0.8]
 [0.4 0.6]]

 p(x, z):
[[0.1 0.4]
 [0.2 0.3]]

 p(x|z):
[[0.2 0.8]
 [0.4 0.6]]

 p(y|z):
[[0.6 0. ]
 [0.  1.4]]


In [49]:
print('\nEntropy of X:')
print(-0.5 * np.log(0.5) -0.5 * np.log(0.5))

print('Entoropy of x/y:')
print( -0.1 * np.log(1/3) -0.2 * np.log(2/3) -0.4 * np.log(4/7) - 0.3 * np.log(3/7))

print('Entoropy of x/z:')
print( -0.1 * np.log(1/3) -0.2 * np.log(2/3) -0.4 * np.log(4/7) - 0.3 * np.log(3/7))

print('\nEntropy of (X/Y) / Z:')
print( -0.1 * np.log(1/3) -0.2 * np.log(2/3) -0.4 * np.log(4/7) - 0.3 * np.log(3/7))





Entropy of X:
0.6931471805599453
Entoropy of x/y:
0.6689899237787742
Entoropy of x/z:
0.6689899237787742

Entropy of (X/Y) / Z:
0.6689899237787742
