In [1]:
import numpy as np
import pandas as pd


In [12]:
# question 5
#P shape: [c,b,a]
p_desc = np.array([[['000', '100'], ['010', '110']], [['001', '101'], ['011', '111']]])
p = np.array([[[3/32, 1/40], [1/4, 3/32]], [[1/32, 1/10], [1/8, 9/32]]])

print(p_desc)
print()
print(p)
print(p.shape)

[[['000' '100']
  ['010' '110']]

 [['001' '101']
  ['011' '111']]]

[[[0.09375 0.025  ]
  [0.25    0.09375]]

 [[0.03125 0.1    ]
  [0.125   0.28125]]]
(2, 2, 2)


In [53]:
dims=['c', 'b', 'a']
for d1 in range(3):
    for d2 in range(d1):
        print(f'Marginal for P({dims[2 - d2 - d1 + 1]}):')
        print(p.sum(axis=(d1, d2)))

print()
for d1 in range(3):
    print(f'Marginals for P({dims[2-d1], dims[2-d1-1]}):')
    print(p.sum(axis=d1))  
    print()
    print(f'Covariance matrix for P({dims[2-d1], dims[2-d1-1]}):')
    print(np.cov(p.sum(axis=d1)))
    print()
    



Marginal for P(a):
[0.5 0.5]
Marginal for P(b):
[0.25 0.75]
Marginal for P(c):
[0.4625 0.5375]

Marginals for P(('a', 'b')):
[[0.125 0.125]
 [0.375 0.375]]

Covariance matrix for P(('a', 'b')):
[[0. 0.]
 [0. 0.]]

Marginals for P(('b', 'c')):
[[0.34375 0.11875]
 [0.15625 0.38125]]

Covariance matrix for P(('b', 'c')):
[[ 0.0253125 -0.0253125]
 [-0.0253125  0.0253125]]

Marginals for P(('c', 'a')):
[[0.11875 0.34375]
 [0.13125 0.40625]]

Covariance matrix for P(('c', 'a')):
[[0.0253125 0.0309375]
 [0.0309375 0.0378125]]

